### ISSUE TITLE
Migration to SpringDoc OpenApi from SpringFox

### ISSUE THREAD

**Issue by evrentan** [evrentan/spring-boot-project-example#1]
Migration to SpringDoc OpenApi from SpringFox will be implemented. Pls check the below link for how-to migrate from SpringFox to SpringDoc OpenApi

https://springdoc.org/#migrating-from-springfox

**Comment by Erkanerkisi** [comment]
Hi Evren,

Can you assign me this issue? Already opened and pr for this enhancement.

Thanks

**Comment by evrentan** [comment]
Hi @Erkanerkisi,
Thanks for the contribution. I have just merged your PR and closing this task. Let's continue :)
